[package]
name = "modsReforged"
version = "0.1.0"
description = ""
authors = ["github@jeykey.net"]
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = "2.33.0"
colored = "2.0.0"
